In [1]:
import numpy as np

# Set NumPy random seed to exactly 42
np.random.seed(42)

# Generate Matrix A: shape (4, 3), random integers range [1, 10] (inclusive)
A = np.random.randint(1, 11, size=(4, 3))

# Generate Matrix B: shape (3, 5), random integers range [1, 10] (inclusive)
B = np.random.randint(1, 11, size=(3, 5))

# Display Matrix A and its shape
print("Matrix A:")
print(A)
print("\nA.shape:", A.shape)

# Display Matrix B and its shape
print("\nMatrix B:")
print(B)
print("\nB.shape:", B.shape)

Matrix A:
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]
 [ 5  4  8]]

A.shape: (4, 3)

Matrix B:
[[ 8  3  6  5  2]
 [ 8  6  2  5  1]
 [10  6  9  1 10]]

B.shape: (3, 5)


In [2]:
# Programmatically validate that inner dimensions match
assert A.shape[1] == B.shape[0], "Matrix dimensions are incompatible for multiplication!"

# Compute matrix product C = A dot B using NumPy operations
C = np.dot(A, B)

# Display Matrix C and its shape
print("Matrix C (A dot B):")
print(C)
print("\nC.shape:", C.shape)

# Verify shape is (4, 5)
assert C.shape == (4, 5), "Matrix C shape is not (4, 5)!"

Matrix C (A dot B):
[[168  93 122  63  98]
 [196 117 134  70 117]
 [160  99 104  58  93]
 [152  87 110  53  94]]

C.shape: (4, 5)


In [ ]:
# 1. Total sum of all elements in C
total_sum = np.sum(C)
print("Total sum of all elements in C:", total_sum)

# 2. Row-wise sums using axis=1
row_sums = np.sum(C, axis=1)
print("Row-wise sums (axis=1):", row_sums)

# 3. Column-wise sums using axis=0
col_sums = np.sum(C, axis=0)
print("Column-wise sums (axis=0):", col_sums)